language: en-US

# General review settings
reviews:
  profile: chill
  high_level_summary: true
  changed_files_summary: true
  review_status: true
  commit_status: true
  auto_review:
    enabled: true

# Disable any test generation or review for unit tests
finishing_touches:
  unit_tests:
    enabled: false

# Tool integrations: basic linting and checks
tools:
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
  yamllint:
    enabled: true
  github-checks:
    enabled: true
    timeout_ms: 90000

# Only include these paths for review
path_filters:
  - "lib/**"
  - "pubspec.yaml"
  - "Makefile"

chat:
  auto_reply: true