include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_unnecessary_containers: error
    prefer_final_parameters: error
    avoid_init_to_null: error
    prefer_relative_imports: warning
    prefer_final_fields: warning
    file_names: error
    avoid_unused_constructor_parameters: warning
    avoid_print: warning
    avoid_multiple_declarations_per_line: error
    camel_case_types: error
    camel_case_extensions: error
    empty_catches: error
linter:
  rules:
    - prefer_const_constructors_in_immutables
    - avoid_init_to_null
    - prefer_final_fields
    - prefer_const_constructors
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - file_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_print
    - avoid_multiple_declarations_per_line
    - camel_case_extensions
    - camel_case_types
    - unnecessary_async
    - unnecessary_breaks
    - use_if_null_to_convert_nulls_to_bools